// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb_AAdOciLx8fc1hxBwraG_Z-S7lozyPc',
    appId: '1:689451026161:web:07c86c5596abc3f3148b50',
    messagingSenderId: '689451026161',
    projectId: 'speak-practice-app-5eaaa',
    authDomain: 'speak-practice-app-5eaaa.firebaseapp.com',
    storageBucket: 'speak-practice-app-5eaaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUybiii-9BemDZmEUCuB71ZZ9LVwlGhQ',
    appId: '1:689451026161:android:e4924571a16c8589148b50',
    messagingSenderId: '689451026161',
    projectId: 'speak-practice-app-5eaaa',
    storageBucket: 'speak-practice-app-5eaaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzv5lsfTqrUOEIybgmu5KFvYb8ir0WUAo',
    appId: '1:689451026161:ios:d1d47b58bd082f91148b50',
    messagingSenderId: '689451026161',
    projectId: 'speak-practice-app-5eaaa',
    storageBucket: 'speak-practice-app-5eaaa.firebasestorage.app',
    iosBundleId: 'com.example.speakPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzv5lsfTqrUOEIybgmu5KFvYb8ir0WUAo',
    appId: '1:689451026161:ios:d1d47b58bd082f91148b50',
    messagingSenderId: '689451026161',
    projectId: 'speak-practice-app-5eaaa',
    storageBucket: 'speak-practice-app-5eaaa.firebasestorage.app',
    iosBundleId: 'com.example.speakPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb_AAdOciLx8fc1hxBwraG_Z-S7lozyPc',
    appId: '1:689451026161:web:9e9022a1b5739f87148b50',
    messagingSenderId: '689451026161',
    projectId: 'speak-practice-app-5eaaa',
    authDomain: 'speak-practice-app-5eaaa.firebaseapp.com',
    storageBucket: 'speak-practice-app-5eaaa.firebasestorage.app',
  );
}
